version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_NAME:-subscriptions}
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-app} -d ${DB_NAME:-subscriptions}"]
      interval: 2s
      timeout: 3s
      retries: 30
    volumes:
      - dbdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:4
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: [
      "-path","/migrations",
      "-database","postgres://${DB_USER:-app}:${DB_PASSWORD:-secret}@db:5432/${DB_NAME:-subscriptions}?sslmode=disable",
      "up"
    ]
    restart: on-failure

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      PORT: 8080
      LOG_LEVEL: info
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-app}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      DB_NAME: ${DB_NAME:-subscriptions}
      DB_SSLMODE: disable
    ports:
      - "8080:8080"

volumes:
  dbdata: {}
